export const questions = [
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What does a funambulist walk on?",
    correct_answer: "A Tight Rope",
    incorrect_answers: ["Broken Glass", "Balls", "The Moon"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "On a dartboard, what number is directly opposite No. 1?",
    correct_answer: "19",
    incorrect_answers: ["20", "12", "15"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What alcoholic drink is made from molasses?",
    correct_answer: "Rum",
    incorrect_answers: ["Gin", "Vodka", "Whisky"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "Which restaurant&#039;s mascot is a clown?",
    correct_answer: "McDonald&#039;s",
    incorrect_answers: ["Whataburger", "Burger King", "Sonic"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which of the following card games revolves around numbers and basic math?",
    correct_answer: "Uno",
    incorrect_answers: ["Go Fish", "Twister", "Munchkin"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is Cynophobia the fear of?",
    correct_answer: "Dogs",
    incorrect_answers: ["Birds", "Flying", "Germs"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question:
      "Terry Gilliam was an animator that worked with which British comedy group?",
    correct_answer: "Monty Python",
    incorrect_answers: [
      "The Goodies&lrm;",
      "The League of Gentlemen&lrm;",
      "The Penny Dreadfuls",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question:
      "When someone is cowardly, they are said to have what color belly?",
    correct_answer: "Yellow",
    incorrect_answers: ["Green", "Red", "Blue"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What are Panama hats made out of?",
    correct_answer: "Straw",
    incorrect_answers: ["Silk", "Hemp", "Flax"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "When was the Playstation 3 released?",
    correct_answer: "November 11, 2006",
    incorrect_answers: [
      "January 8, 2007",
      "December 25, 2007",
      "July 16, 2006",
    ],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "Gumbo is a stew that originated in Louisiana.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "Nutella is produced by the German company Ferrero.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "Bulls are attracted to the color red.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question:
      "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "The Sun rises from the North.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question:
      "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "Pluto is a planet.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "The Lego Group was founded in 1932.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question:
      "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question:
      "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which of the following sports is not part of the triathlon?",
    correct_answer: "Horse-Riding",
    incorrect_answers: ["Cycling", "Swimming", "Running"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "In what sport is a &quot;shuttlecock&quot; used?",
    correct_answer: "Badminton",
    incorrect_answers: ["Table Tennis", "Rugby", "Cricket"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "The Rio 2016 Summer Olympics held it&#039;s closing ceremony on what date?",
    correct_answer: "August 21",
    incorrect_answers: ["August 23", "August 19", "August 17"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who won the 2015 Formula 1 World Championship?",
    correct_answer: "Lewis Hamilton",
    incorrect_answers: ["Nico Rosberg", "Sebastian Vettel", "Jenson Button"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which driver has been the Formula 1 world champion for a record 7 times?",
    correct_answer: "Michael Schumacher",
    incorrect_answers: ["Ayrton Senna", "Fernando Alonso", "Jim Clark"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "What was the final score of the Germany vs. Brazil 2014 FIFA World Cup match?",
    correct_answer: "7 - 1",
    incorrect_answers: ["0 - 1", "3 - 4", "16 - 0"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "This Canadian television sportscaster is known for his &quot;Hockey Night in Canada&quot; role, a commentary show during hockey games.",
    correct_answer: "Don Cherry",
    incorrect_answers: ["Don McKellar", "Don Taylor ", "Donald Sutherland"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "When was the first official international game played?",
    correct_answer: "1872",
    incorrect_answers: ["1880", "1863", "1865"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "What is the most common type of pitch thrown by pitchers in baseball?",
    correct_answer: "Fastball",
    incorrect_answers: ["Slowball", "Screwball", "Palmball"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who won the UEFA Champions League in 2017?",
    correct_answer: "Real Madrid C.F.",
    incorrect_answers: ["Atletico Madrid", "AS Monaco FC", "Juventus F.C."],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question:
      "The Axolotl is an amphibian that can spend its whole life in a larval state.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "A slug&rsquo;s blood is green.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "Kangaroos keep food in their pouches next to their children.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "A bear does NOT defecate during hibernation. ",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question:
      "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "A flock of crows is known as a homicide.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "A caterpillar has more muscles than humans do.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "The Killer Whale is considered a type of dolphin.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question: "Rabbits are carnivores.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Animals",
    type: "boolean",
    difficulty: "easy",
    question:
      "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "In the Morse code, which letter is indicated by 3 dots? ",
    correct_answer: "S",
    incorrect_answers: ["O", "A", "C"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is a &quot;dakimakura&quot;?",
    correct_answer: "A body pillow",
    incorrect_answers: [
      "A Chinese meal, essentially composed of fish",
      "A yoga posture",
      "A word used to describe two people who truly love each other",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "What did the Spanish autonomous community of Catalonia ban in 2010, that took effect in 2012?",
    correct_answer: "Bullfighting",
    incorrect_answers: ["Fiestas", "Flamenco", "Mariachi"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the Portuguese word for &quot;Brazil&quot;?",
    correct_answer: "Brasil",
    incorrect_answers: ["Brazil", "Brasilia", "Bras&iacute;l"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Where does water from Poland Spring water bottles come from?",
    correct_answer: "Maine, United States",
    incorrect_answers: ["Hesse, Germany", "Masovia, Poland", "Bavaria, Poland"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is a Burgee?",
    correct_answer: "A flag",
    incorrect_answers: ["A rope", "A window", "A type of food"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "In a 1994 CBS interview, Microsoft co-founder Bill Gates performed what unusual trick on camera?",
    correct_answer: "Jumping over an office chair",
    incorrect_answers: [
      "Jumping backwards over a desk",
      "Standing on his head",
      "Typing on a keyboard during a handstand",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "What was the name given to Japanese military dictators who ruled the country through the 12th and 19th Century?",
    correct_answer: "Shogun",
    incorrect_answers: ["Ninja", "Samurai", "Shinobi"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which American manufactured submachine gun was informally known by the American soldiers that used it as &quot;Grease Gun&quot;?",
    correct_answer: "M3",
    incorrect_answers: ["Colt 9mm", "Thompson", "MAC-10"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "Linus Pauling, one of the only winners of multiple Nobel Prizes, earned his Nobel Prizes in Chemistry and what?",
    correct_answer: "Peace",
    incorrect_answers: ["Physics", "Economics", "Physiology/Medicine"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question:
      "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question: "Coca-Cola&#039;s original colour was green.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question: "Furby was released in 1998.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question: "An eggplant is a vegetable.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question:
      "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question: "The French word to travel is &quot;Travail&quot;",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question:
      "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question:
      "The commercial UK channel ITV stands for &quot;International Television&quot;.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question:
      "&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "medium",
    question:
      "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "According to the BBPA, what is the most common pub name in the UK?",
    correct_answer: "Red Lion",
    incorrect_answers: ["Royal Oak", "White Hart", "King&#039;s Head"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Rolex is a company that specializes in what type of product?",
    correct_answer: "Watches",
    incorrect_answers: ["Cars", "Computers", "Sports equipment"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "A doctor with a PhD is a doctor of what?",
    correct_answer: "Philosophy",
    incorrect_answers: ["Psychology", "Phrenology", "Physical Therapy"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "After how many years would you celebrate your crystal anniversary?",
    correct_answer: "15",
    incorrect_answers: ["20", "10", "25"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question:
      "What did the Spanish autonomous community of Catalonia ban in 2010, that took effect in 2012?",
    correct_answer: "Bullfighting",
    incorrect_answers: ["Fiestas", "Flamenco", "Mariachi"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "When was Nintendo founded?",
    correct_answer: "September 23rd, 1889",
    incorrect_answers: [
      "October 19th, 1891",
      "March 4th, 1887",
      "December 27th, 1894",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "In what year was McDonald&#039;s founded?",
    correct_answer: "1955",
    incorrect_answers: ["1964", "1951", "1947"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Which country drives on the left side of the road?",
    correct_answer: "Japan",
    incorrect_answers: ["Germany", "Russia", "China"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the star sign of someone born on Valentines day?",
    correct_answer: "Aquarius",
    incorrect_answers: ["Pisces", "Capricorn", "Scorpio"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the full title of the Prime Minister of the UK?",
    correct_answer: "First Lord of the Treasury",
    incorrect_answers: [
      "Duke of Cambridge",
      "Her Majesty&#039;s Loyal Opposition",
      "Manager of the Crown Estate",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Electronic music producer Kygo&#039;s popularity skyrocketed after a certain remix. Which song did he remix?",
    correct_answer: "Ed Sheeran - I See Fire",
    incorrect_answers: [
      "Marvin Gaye - Sexual Healing",
      "Coldplay - Midnight",
      "a-ha - Take On Me",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What year was Queen Elizabeth II born?",
    correct_answer: "1926",
    incorrect_answers: ["1923", "1929", "1930"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "Which of the following chemicals are found in eggplant seeds?",
    correct_answer: "Nicotine",
    incorrect_answers: ["Mescaline", "Cyanide", "Psilocybin"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of the following is an existing family in &quot;The Sims&quot;?",
    correct_answer: "The Goth Family",
    incorrect_answers: [
      "The Family",
      "The Simoleon Family",
      "The Proud Family",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which musician has collaborated with American producer Porter Robinson and released the 2016 song &quot;Shelter&quot;?",
    correct_answer: "Madeon",
    incorrect_answers: ["Mat Zo", "deadmau5", "Zedd"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Disney&#039;s Haunted Mansion is home to a trio of Hitchhiking Ghosts. Which of these is NOT one of them?",
    correct_answer: "Harry",
    incorrect_answers: ["Gus", "Phineas", "Ezra"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "How long did it take the motorized window washers of the original World Trade Center to clean the entire exterior of the building?",
    correct_answer: "1 Month",
    incorrect_answers: ["3 Weeks", "1 Week", "2 Months"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of the following languages does NOT use gender as a part of its grammar?",
    correct_answer: "Turkish",
    incorrect_answers: ["German", "Danish", "Polish"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "According to the 2014-2015 Australian Bureau of Statistics, what percentage of Australians were born overseas?",
    correct_answer: "28%",
    incorrect_answers: ["13%", "20%", "7%"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What was Bank of America originally established as?",
    correct_answer: "Bank of Italy",
    incorrect_answers: [
      "Bank of Long Island",
      "Bank of Pennsylvania",
      "Bank of Charlotte",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What is the romanized Chinese word for &quot;airplane&quot;?",
    correct_answer: "Feiji",
    incorrect_answers: ["Qiche", "Zongxian", "Huojian"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What is the romanized Arabic word for &quot;moon&quot;?",
    correct_answer: "Qamar",
    incorrect_answers: ["Najma", "Kawkab", "Shams"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Disney&#039;s Haunted Mansion is home to a trio of Hitchhiking Ghosts. Which of these is NOT one of them?",
    correct_answer: "Harry",
    incorrect_answers: ["Gus", "Phineas", "Ezra"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "How long did it take the motorized window washers of the original World Trade Center to clean the entire exterior of the building?",
    correct_answer: "1 Month",
    incorrect_answers: ["3 Weeks", "1 Week", "2 Months"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "What does the Latin phrase &quot;Veni, vidi, vici&quot; translate into English?",
    correct_answer: "I came, I saw, I conquered",
    incorrect_answers: [
      "See no evil, hear no evil, speak no evil",
      "Life, liberty, and happiness",
      "Past, present, and future",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "In flight systems, what does the initialism &quot;TCAS&quot; stand for?",
    correct_answer: "Traffic Collision Avoidance System",
    incorrect_answers: [
      "Traffic Communication Alert System",
      "Traffic Configuration Alignment System",
      "Traffic Call-sign Abbreviation System",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "Chartreuse is a color between yellow and what?",
    correct_answer: "Green",
    incorrect_answers: ["Red", "Black", "Purple"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "The Quadrangularis Reversum is best described as which of the following?",
    correct_answer: "A percussion instrument",
    incorrect_answers: [
      "A building in Oxford University",
      "A chess move",
      "A geometric theorem",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "The word &quot;abulia&quot; means which of the following?",
    correct_answer: "The inability to make decisions",
    incorrect_answers: [
      "The inability to stand up",
      "The inability to concentrate on anything",
      "A feverish desire to rip one&#039;s clothes off",
    ],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of these cities does NOT have a United States Minting location?",
    correct_answer: "St. Louis, MO",
    incorrect_answers: [
      "San Fransisco, CA",
      "Philidelphia, PA",
      "West Point, NY",
    ],
  },
]
